### ISSUE TITLE
control doesn't work

### ISSUE THREAD

**Issue by valmil2000** [mSimon12/multiple_quadrotors#4]
Hey first of all thanks a lot for sharing your work! I tried to do the integration into ros melodic and gazebo 9 on my own but couldn't figure it out...
The installation went well but once I try to start moving the drone 
( for example: rosrun quadrotor_control_system move_drone.py UAV_1 5.0 5.0 10.0 0.0)
I get the following error message:
[rosrun] Couldn't find executable named move_drone.py below /home/developer/work/src/multiple_quadrotors/src/quadrotor/quadrotor_control_system
[rosrun] Found the following, but they're either not files,
[rosrun] or not executable:
[rosrun]   /home/developer/work/src/multiple_quadrotors/src/quadrotor/quadrotor_control_system/src/move_drone.py

do you have an idea what might be the problem? I didn't change anything and unpaused gazebo...

I'd appreciate it a lot!

**Comment by mSimon12** [comment]
Hello @valmil2000, sorry for the delay.

I just uploaded a new version of the code with some improvements related to trajectory planning. I suggest you make the changes and try again.

If the problem persists, try to check if move_drone.py has execute permission (use the command `ls -all`). Otherwise, you can use `chmod 777 -R src/` to make all files executable.

I hope it helps. Goodbye.
